// <auto-generated />
using System;
using KlearviewQuotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlearviewQuotes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411022343_ModifyWorkOrderTable")]
    partial class ModifyWorkOrderTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBillingLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultServiceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxExempt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Agreement", b =>
                {
                    b.Property<string>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReasonOther")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractAmountTaxable")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractChargeForProducts")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractChargeForServices")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractPeriodAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractProrated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBillingContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultServiceContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceInitialEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceInitialStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceScheduleDelay")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceSchedulePeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsRenewal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalAgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpfrontInvoicingDaysAhead")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpfrontInvoicingTimeToCreateInvoice")
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.ServiceLocation", b =>
                {
                    b.Property<string>("ServiceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceMemo")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateAbbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceLocationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ServiceLocations");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualCompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingLocationBillingMemo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReasonOther")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Closed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommittedResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeekPreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurationAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndOfCommitmentWindow")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTimePreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndingEligibleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedCompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedTimeOfArrival")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNote")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerformedByResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSubTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLocationServiceMemo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceSubTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartOfCommitmentWindow")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTimePreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartingEligibleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnassignedResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Zone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Agreement", b =>
                {
                    b.HasOne("KlearviewQuotes.Models.Clients.Account", "Account")
                        .WithMany("Agreements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlearviewQuotes.Models.Clients.ServiceLocation", "ServiceLocation")
                        .WithMany("Agreements")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.ServiceLocation", b =>
                {
                    b.HasOne("KlearviewQuotes.Models.Clients.Account", "Account")
                        .WithMany("ServiceLocations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlearviewQuotes.Models.Clients.Zone", "Zone")
                        .WithMany("ServiceLocations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.WorkOrder", b =>
                {
                    b.HasOne("KlearviewQuotes.Models.Clients.Account", "Account")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlearviewQuotes.Models.Clients.ServiceLocation", "ServiceLocation")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Account", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("ServiceLocations");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.ServiceLocation", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Zone", b =>
                {
                    b.Navigation("ServiceLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
