// <auto-generated />
using System;
using KlearviewQuotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlearviewQuotes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405234507_AddServiceLocation")]
    partial class AddServiceLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBillingLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultServiceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxExempt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.ServiceLocation", b =>
                {
                    b.Property<string>("ServiceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceMemo")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateAbbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceLocationId");

                    b.HasIndex("AccountId");

                    b.ToTable("ServiceLocations");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.ServiceLocation", b =>
                {
                    b.HasOne("KlearviewQuotes.Models.Clients.Account", "Account")
                        .WithMany("ServiceLocations")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Account", b =>
                {
                    b.Navigation("ServiceLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
