// <auto-generated />
using KlearviewQuotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlearviewQuotes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405225033_FixSpelling")]
    partial class FixSpelling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("KlearviewQuotes.Models.Clients.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBillingLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultServiceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxExempt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
